# Generated by Django 3.2.9 on 2022-04-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_auto_20220414_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
